baseURL = "https://holywritings.net/"
title = "Bahá'í Prayers"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "Share prayers with people in their own language"
  rtlLanguages = ["ar", "fa", "ur", "he", "ug", "ar-translit", "fa-translit"]
